compressionLevel: mixed

enableColors: true

enableGlobalCache: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@scaffold-ui/components"
  - "@scaffold-ui/debug-contracts"
  - "@scaffold-ui/hooks"
  - burner-connector

yarnPath: .yarn/releases/yarn-4.13.0.cjs
