enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 2880 # 2880 minutes = 2 days

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
