compressionLevel: mixed

enableColors: true

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  [
    "@scaffold-ui/components",
    "@scaffold-ui/debug-contracts",
    "@scaffold-ui/hooks",
    "burner-connector",
    "react@19.2.*",
    "react-dom@19.2.*",
    "next@15.2.*",
  ]
