/**
 * This file is autogenerated by Scaffold-ETH.
 * you should not edit it manually, any changes to this file will be automatically reverted by pre-commit hook.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedLocalhostContracts = {} as const;

export default deployedLocalhostContracts satisfies GenericContractsDeclaration;
