/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    HonkVerifier: {
      address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      abi: [
        {
          inputs: [],
          name: "ProofLengthWrong",
          type: "error",
        },
        {
          inputs: [],
          name: "PublicInputsLengthWrong",
          type: "error",
        },
        {
          inputs: [],
          name: "ShpleminiFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "SumcheckFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "proof",
              type: "bytes",
            },
            {
              internalType: "bytes32[]",
              name: "publicInputs",
              type: "bytes32[]",
            },
          ],
          name: "verify",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    LeanIMT: {
      address: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
      abi: [
        {
          inputs: [],
          name: "LeafAlreadyExists",
          type: "error",
        },
        {
          inputs: [],
          name: "LeafCannotBeZero",
          type: "error",
        },
        {
          inputs: [],
          name: "LeafDoesNotExist",
          type: "error",
        },
        {
          inputs: [],
          name: "LeafGreaterThanSnarkScalarField",
          type: "error",
        },
        {
          inputs: [],
          name: "WrongSiblingNodes",
          type: "error",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 4,
    },
    PoseidonT3: {
      address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256[2]",
              name: "",
              type: "uint256[2]",
            },
          ],
          name: "hash",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
    Voting: {
      address: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "_verifier",
              type: "address",
            },
            {
              internalType: "string",
              name: "_question",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "commitment",
              type: "uint256",
            },
          ],
          name: "Voting__CommitmentAlreadyAdded",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__EmptyTree",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__InvalidProof",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__InvalidRoot",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__NotAllowedToVote",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "nullifierHash",
              type: "bytes32",
            },
          ],
          name: "Voting__NullifierHashAlreadyUsed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "NewLeaf",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "nullifierHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "voter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "vote",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalYes",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalNo",
              type: "uint256",
            },
          ],
          name: "VoteCast",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "voter",
              type: "address",
            },
          ],
          name: "VoterAdded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "voters",
              type: "address[]",
            },
            {
              internalType: "bool[]",
              name: "statuses",
              type: "bool[]",
            },
          ],
          name: "addVoters",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_voter",
              type: "address",
            },
          ],
          name: "getVoterData",
          outputs: [
            {
              internalType: "bool",
              name: "voter",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "registered",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getVotingData",
          outputs: [
            {
              internalType: "string",
              name: "question",
              type: "string",
            },
            {
              internalType: "address",
              name: "contractOwner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "yesVotes",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "noVotes",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "size",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "depth",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "root",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_verifier",
          outputs: [
            {
              internalType: "contract IVerifier",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_commitment",
              type: "uint256",
            },
          ],
          name: "register",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "_proof",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "_nullifierHash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "_root",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "_vote",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "_depth",
              type: "bytes32",
            },
          ],
          name: "vote",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        owner: "npm/@openzeppelin/contracts@5.0.2/access/Ownable.sol",
        renounceOwnership: "npm/@openzeppelin/contracts@5.0.2/access/Ownable.sol",
        transferOwnership: "npm/@openzeppelin/contracts@5.0.2/access/Ownable.sol",
      },
      deployedOnBlock: 5,
    },
    YourContract: {
      address: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
  11155420: {
    HonkVerifier: {
      address: "0x0930d305116f12cac3a9d4b7d60d13fd3fb8e8ec",
      abi: [
        {
          inputs: [],
          name: "ProofLengthWrong",
          type: "error",
        },
        {
          inputs: [],
          name: "PublicInputsLengthWrong",
          type: "error",
        },
        {
          inputs: [],
          name: "ShpleminiFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "SumcheckFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "proof",
              type: "bytes",
            },
            {
              internalType: "bytes32[]",
              name: "publicInputs",
              type: "bytes32[]",
            },
          ],
          name: "verify",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 43347333,
    },
    LeanIMT: {
      address: "0xc28f1298f7e7b5e76f258c5d1130ef18e3514350",
      abi: [
        {
          inputs: [],
          name: "LeafAlreadyExists",
          type: "error",
        },
        {
          inputs: [],
          name: "LeafCannotBeZero",
          type: "error",
        },
        {
          inputs: [],
          name: "LeafDoesNotExist",
          type: "error",
        },
        {
          inputs: [],
          name: "LeafGreaterThanSnarkScalarField",
          type: "error",
        },
        {
          inputs: [],
          name: "WrongSiblingNodes",
          type: "error",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 43347334,
    },
    PoseidonT3: {
      address: "0x955c98ef05a2e280e82942e4242a8d3db2a3f9bd",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256[2]",
              name: "",
              type: "uint256[2]",
            },
          ],
          name: "hash",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 43347334,
    },
    Voting: {
      address: "0xb4fbd5c9e61ecb3472dc778079a8cb15787d2290",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "_verifier",
              type: "address",
            },
            {
              internalType: "string",
              name: "_question",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "commitment",
              type: "uint256",
            },
          ],
          name: "Voting__CommitmentAlreadyAdded",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__EmptyTree",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__InvalidProof",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__InvalidRoot",
          type: "error",
        },
        {
          inputs: [],
          name: "Voting__NotAllowedToVote",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "nullifierHash",
              type: "bytes32",
            },
          ],
          name: "Voting__NullifierHashAlreadyUsed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "NewLeaf",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "nullifierHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "voter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "vote",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalYes",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalNo",
              type: "uint256",
            },
          ],
          name: "VoteCast",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "voter",
              type: "address",
            },
          ],
          name: "VoterAdded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "voters",
              type: "address[]",
            },
            {
              internalType: "bool[]",
              name: "statuses",
              type: "bool[]",
            },
          ],
          name: "addVoters",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_voter",
              type: "address",
            },
          ],
          name: "getVoterData",
          outputs: [
            {
              internalType: "bool",
              name: "voter",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "registered",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getVotingData",
          outputs: [
            {
              internalType: "string",
              name: "question",
              type: "string",
            },
            {
              internalType: "address",
              name: "contractOwner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "yesVotes",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "noVotes",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "size",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "depth",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "root",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_verifier",
          outputs: [
            {
              internalType: "contract IVerifier",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_commitment",
              type: "uint256",
            },
          ],
          name: "register",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "_proof",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "_nullifierHash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "_root",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "_vote",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "_depth",
              type: "bytes32",
            },
          ],
          name: "vote",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        owner: "npm/@openzeppelin/contracts@5.0.2/access/Ownable.sol",
        renounceOwnership: "npm/@openzeppelin/contracts@5.0.2/access/Ownable.sol",
        transferOwnership: "npm/@openzeppelin/contracts@5.0.2/access/Ownable.sol",
      },
      deployedOnBlock: 43347565,
    },
    YourContract: {
      address: "0x22cf0318fa317329857a9931f1d770cde4c08472",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 43347332,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
