/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedLocalhostContracts = {} as const;

export default deployedLocalhostContracts satisfies GenericContractsDeclaration;
